### ISSUE TITLE
Relative Path of two methods in index.html

### ISSUE THREAD

**Issue by tony-kunliu** [E-Movement/SmartVote#2]
Couldn't figure out the right relative paths for calling jumpToVoterHome and jumpToOrganizerHome.
Could be caused by other bugs.
Anyone can help with that?

**Comment by zqa19** [comment]
Use ../ to denote parent folder and ./ to denote current folder.

**Comment by tony-kunliu** [comment]
I tried, doesn't work. Weird.

On Saturday, 25 April 2015, zqa19 notifications@github.com wrote:

> Use ../ to denote parent folder and ./ to denote current folder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/E-Movement/SmartVote/issues/2#issuecomment-96120477.

## 

_Kun Liu_
_Master of Computing_
_Australian National University_
_Email: kunliu89@gmail.com kunliu89@gmail.com_
_Phone#: 0416-575-688_

**Comment by zqa19** [comment]
Your index.html is in /SmartVote and OrganizerHome.html is in /SmartVote/templates/OrganizerHome/, so you should write the path as ./templates/OrganizerHome/OrganizerHome.html.

**Comment by tony-kunliu** [comment]
tried that already. Still didn't work.
Will try more  later.
On Saturday, 25 April 2015, zqa19 notifications@github.com wrote:

> Your index.html is in /SmartVote and OrganizerHome.html is in
> /SmartVote/templates/OrganizerHome/, so you should write the path as
> ./templates/OrganizerHome/OrganizerHome.html.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/E-Movement/SmartVote/issues/2#issuecomment-96122200.

## 

_Kun Liu_
_Master of Computing_
_Australian National University_
_Email: kunliu89@gmail.com kunliu89@gmail.com_
_Phone#: 0416-575-688_

**Comment by zqa19** [comment]
There is a typo in the name of the html page, it is supposed to be OrganizerHome.html but not OrganiserHome.html.

Please fully understand the usage of form tag, if you put the button outside form tag, it works.

And the scripts are supposed to be written in one place, not some in head and some in body.

**Comment by zqa19** [comment]
And about div tag, it is good to use to put those things you want together, but using div tag for a single component is pointless.

**Comment by tony-kunliu** [comment]
Thanks a lot.  Will be more careful with those you mentioned.

On Saturday, 25 April 2015, zqa19 notifications@github.com wrote:

> There is a typo in the name of the html page, it is supposed to be
> OrganizerHome.html but not OrganiserHome.html.
> 
> Please fully understand the usage of form tag, if you put the button
> outside form tag, it works.
> 
> And the scripts are supposed to be written in one place, not some in head
> and some in body.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/E-Movement/SmartVote/issues/2#issuecomment-96135074.

## 

_Kun Liu_
_Master of Computing_
_Australian National University_
_Email: kunliu89@gmail.com kunliu89@gmail.com_
_Phone#: 0416-575-688_
